CREATE DATABASE test;

USE test;

CREATE TABLE tempTbl(
    TO_USERID VARCHAR(10),
    TO_PASSWORD VARCHAR(20),
    TO_TEL VARCHAR(10),
    TO_BIRTHDAY DATETIME,
    TO_ADDRESS VARCHAR(100),
    TO_TOROKUBI DATETIME
);